// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0UZQ6TzVi2HGY_S8vvPZ0Wr7ZKXCZgE',
    appId: '1:228558641396:web:cce02248962257d4d526a1',
    messagingSenderId: '228558641396',
    projectId: 'gas-leak-safety',
    authDomain: 'gas-leak-safety.firebaseapp.com',
    storageBucket: 'gas-leak-safety.appspot.com',
    measurementId: 'G-28DVRPECT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvz4RnCuSJ0gmiqXy7-fFNdFcjt3pv3xU',
    appId: '1:228558641396:android:55a7f0a83d012f33d526a1',
    messagingSenderId: '228558641396',
    projectId: 'gas-leak-safety',
    storageBucket: 'gas-leak-safety.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoigQU4LRiVemNnfnJLorUTi3CQVA3YT8',
    appId: '1:228558641396:ios:494264f64446ae14d526a1',
    messagingSenderId: '228558641396',
    projectId: 'gas-leak-safety',
    storageBucket: 'gas-leak-safety.appspot.com',
    iosClientId: '228558641396-orngun9q7483ddnrqr0ja0k49790m7ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasLeakSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoigQU4LRiVemNnfnJLorUTi3CQVA3YT8',
    appId: '1:228558641396:ios:494264f64446ae14d526a1',
    messagingSenderId: '228558641396',
    projectId: 'gas-leak-safety',
    storageBucket: 'gas-leak-safety.appspot.com',
    iosClientId: '228558641396-orngun9q7483ddnrqr0ja0k49790m7ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasLeakSafety',
  );
}
